#ifndef DMR_DEMIRBAS_LISTESI_OPEN_H
#define DMR_DEMIRBAS_LISTESI_OPEN_H

#include <QString>
class QWidget;

void OPEN_DMR_DEMIRBAS_LISTESI_BATCH ( QWidget * parent);
QString OPEN_DMR_DEMIRBAS_LISTESI ( DMR_RAPOR_VARS * DMR_RV );

#endif // DMR_DEMIRBAS_LISTESI_OPEN_H
