#ifndef DMR_AMORTISMAN_AYIRMA_BATCH_OPEN_H
#define DMR_AMORTISMAN_AYIRMA_BATCH_OPEN_H

class QWidget;

void OPEN_DMR_AMORTISMAN_AYIRMA_BATCH ( QWidget * parent);

#endif // DMR_AMORTISMAN_AYIRMA_BATCH_OPEN_H
