#ifndef DMR_DEMIRBAS_LISTESI_BATCH_OPEN_H
#define DMR_DEMIRBAS_LISTESI_BATCH_OPEN_H

class QWidget;

void OPEN_DMR_DEMIRBAS_LISTESI_BATCH ( QWidget * parent );

#endif // DMR_DEMIRBAS_LISTESI_BATCH_OPEN_H
