#ifndef DMR_YENIDEN_DEGERLEME_BATCH_OPEN_H
#define DMR_YENIDEN_DEGERLEME_BATCH_OPEN_H

class QWidget;

void OPEN_DMR_YENIDEN_DEGERLEME_BATCH ( QWidget * parent);

#endif // DMR_YENIDEN_DEGERLEME_BATCH_OPEN_H
