#ifndef CEKSENET_ENUM_H
#define CEKSENET_ENUM_H

enum CEK_SENET_POZISYONU {
    ENUM_PORTFOYDE                  = 1,
    ENUM_BNK_TEMINAT_VERILDI        = 2,
    ENUM_BNK_TAHSILAT_VERILDI       = 3,
    ENUM_TAHSIL_EDILDI_NKT          = 4,
    ENUM_TAHSIL_EDILDI_HESABA       = 5,
    ENUM_SATICIYA_VERILDI           = 6,
    ENUM_KARSILIKSIZ                = 7,
    ENUM_PROTESTOLU                 = 8,
    ENUM_MUS_IADE_EDILDI            = 9,
    ENUM_ODENDI_NKT                 = 10,
    ENUM_ODENDI_HESAPTAN            = 11,
    ENUM_SUPHELI_ALACAK             = 12,
    ENUM_TAHSIL_EDILEMEYEN          = 13,
    ENUM_IPTAL                      = 14,
    ENUM_TUM_POZISYONLAR            = 15
};

enum CEK_SNT_BORDROSU_ISLEMLERI {
    ENUM_CEK_BNK_TEMINATA_VERILDI   = 1,
    ENUM_CEK_BNK_TAHSILATA_VERILDI  = 2,
    ENUM_CEK_TAHSIL_EDILDI_NKT      = 3,
    ENUM_CEK_TAHSIL_EDILDI_HESABA   = 4,
    ENUM_CEK_SATICIYA_VERILDI       = 5,
    ENUM_CEK_KARSILIKSIZ            = 6,
    ENUM_CEK_PROTESTOLU             = 7,
    ENUM_CEK_MUS_IADE_EDILDI        = 8,
    ENUM_CEK_ODENDI_NKT             = 9,
    ENUM_CEK_ODENDI_HESAPTAN        = 10,
    ENUM_CEK_TAHSIL_EDILEMEYEN      = 11,
    ENUM_CEK_IADE_ALINDI_BANKADAN   = 12,
    ENUM_CEK_IADE_ALINDI_SATICIDAN  = 13,
    ENUM_CEK_SUPHELI_ALACAK         = 14,
    ENUM_CEK_IPTAL                  = 15,
    ENUM_CEK_MUSTERIDEN_ALINDI      = 16,
    ENUM_TUM_BORDROLAR              = 17
};

//! SADECE ACILIS FISINDE KULLANILIYOR.
enum CEK_SNT_ACILIS_BORDROSU_ISLEM_TURLERI {
    ENUM_CEK_ACILIS_BRD_SATICIYA_VER_FIRMA_CEK      = 10,
    ENUM_CEK_ACILIS_BRD_SATICIYA_VER_FIRMA_SENET    = 20,
    ENUM_CEK_ACILIS_BRD_SATICIYA_VER_MUS_CEK        = 30,
    ENUM_CEK_ACILIS_BRD_SATICIYA_VER_MUS_SENET      = 40,
    ENUM_CEK_ACILIS_BRD_BNK_TEMINAT_MUS_CEK    = 50,
    ENUM_CEK_ACILIS_BRD_BNK_TEMINAT_MUS_SENET  = 60,
    ENUM_CEK_ACILIS_BRD_BNK_TAHSILAT_MUS_CEK   = 70,
    ENUM_CEK_ACILIS_BRD_BNK_TAHSILAT_MUS_SENET = 80,
    ENUM_CEK_ACILIS_BRD_KARSILIKSIZ_MUS_CEK    = 90,
    ENUM_CEK_ACILIS_BRD_PROTESTOLU_MUS_SENET   = 100,
    ENUM_CEK_ACILIS_BRD_SUP_ALACAK_MUS_CEK     = 110,
    ENUM_CEK_ACILIS_BRD_SUP_ALACAK_MUS_SENET   = 120,
    ENUM_CEK_ACILIS_BRD_PORTFOYDE_MUS_CEK      = 130,
    ENUM_CEK_ACILIS_BRD_PORTFOYDE_MUS_SENET    = 140
};
//! END

enum CEK_SNT_ENTEGRASYON_BORDROSU_ISLEM_TURLERI {
    ENUM_CEK_ENT_BRD_SATICIYA_VER_FIRMA_CEK    = 10,
    ENUM_CEK_ENT_BRD_SATICIYA_VER_FIRMA_SENET  = 20,
    ENUM_CEK_ENT_BRD_SATICIYA_VER_MUS_CEK      = 30,
    ENUM_CEK_ENT_BRD_SATICIYA_VER_MUS_SENET    = 40,
    ENUM_CEK_ENT_BRD_MUS_CEK_ALINDI_MUS_CEK    = 50,
    ENUM_CEK_ENT_BRD_MUS_CEK_ALINDI_MUS_SENET  = 60
};

enum CEK_SENET_HEPSI {
    ENUM_CEK   = 1,
    ENUM_SENET = 2,
    ENUM_HEPSI = 3
};

enum BORDRO_TURLERI {
    ENUM_FIRMA_CEK_BORDROSU        = 1,
    ENUM_FIRMA_SENET_BORDROSU      = 2,
    ENUM_MUSTERI_CEK_BORDROSU      = 3,
    ENUM_MUSTERI_SENET_BORDROSU    = 4,
    ENUM_CEK_SENET_ACILIS_BORDROSU = 5
};

enum CEKLER_SENETLER {
    ENUM_MUSTERI_CEK_SENEDI        = 1,
    ENUM_KENDI_CEK_SENEDIMIZ       = 2,
    ENUM_TUM_CEK_SENETLER          = 3
};

enum CEK_SENET_TURU {
    ENUM_CEK_SENET_FISI            = 10,
    ENUM_CEK_SENET_ENT_FISI        = 20
};

#endif // CEKSENET_ENUM_H
