#ifndef CEK_LISTESI_RAPORU_OPEN_H
#define CEK_LISTESI_RAPORU_OPEN_H

class QString;
struct CEK_RAPOR_VARS;


QString GET_CEK_LISTESI_RAPORU                       ( CEK_RAPOR_VARS * P_CEK_RV);

#endif // CEK_LISTESI_RAPORU_OPEN_H
