#ifndef E9_KUL_KITAPCIGI_VE_YARDIM_SAYFASI_BATCH_OPEN_H
#define E9_KUL_KITAPCIGI_VE_YARDIM_SAYFASI_BATCH_OPEN_H
class QWidget;

void OPEN_E9_KUL_KITAPCIGI_VE_YARDIM_SAYFASI_BATCH ( int p_kitapcik_mi, QWidget * parent );

#endif // E9_KUL_KITAPCIGI_VE_YARDIM_SAYFASI_BATCH_OPEN_H
