#ifndef ADRES_ENUM_H
#define ADRES_ENUM_H


enum ADRES_RAPOR_TURLERI {
    ADRES_ILETISIM_RAPORU   = 0,
    ADRES_ETIKETLERI_RAPORU = 1,
    TOPLU_MAIL_GONDERIMI    = 2,
    ADRES_BILGILERI_RAPORU  = 3,
    TOPLU_SMS_GONDERIMI     = 4
};

enum ADRES_ARAMA_ISLEM_TURU {
    ADRES_EXPORT_ISLEMI = 20,
    ADRES_ARAMA_ISLEMI  = 21
};


#endif // ADRES_ENUM_H
