#ifndef ADRES_TOPLU_MAIL_GONDERIMI_BATCH_OPEN_H
#define ADRES_TOPLU_MAIL_GONDERIMI_BATCH_OPEN_H

#include <QStringList>
class QWidget;

void OPEN_ADRES_TOPLU_MAIL_GONDERIMI_BATCH ( QStringList P_TOPLU_MAIL_BILGILERI, QWidget * parent    );

#endif // ADRES_TOPLU_MAIL_GONDERIMI_BATCH_OPEN_H
