#ifndef ADRES_ETIKETLERI_BATCH_OPEN_H
#define ADRES_ETIKETLERI_BATCH_OPEN_H

void OPEN_ADRES_ETIKETLERI_BATCH ( QStringList P_ADRES_ETIKET_BILGILERI, QWidget * parent );

#endif // ADRES_ETIKETLERI_BATCH_OPEN_H
