#ifndef STOK_UURN_LISTESI_RAPORU_OPEN_H
#define STOK_UURN_LISTESI_RAPORU_OPEN_H

class QString;
struct STOK_RAPOR_VARS;

QString             GET_STOK_URUN_LISTESI_RAPORU            ( STOK_RAPOR_VARS *);

#endif // STOK_UURN_LISTESI_RAPORU_OPEN_H
