#ifndef STOK_DETAYLAR_BATCH_OPEN_H
#define STOK_DETAYLAR_BATCH_OPEN_H

struct STOK_DETAYLAR_STRUCT;

bool                OPEN_STOK_DETAYLAR_BATCH ( STOK_DETAYLAR_STRUCT * P_STOK_DETAYLAR ,QWidget * parent );

#endif // STOK_DETAYLAR_BATCH_OPEN_H
