#ifndef STOK_EKSTRESI_RAPORU_OPEN_H
#define STOK_EKSTRESI_RAPORU_OPEN_H

struct STOK_RAPOR_VARS;

QString             GET_STOK_EKSTRESI_RAPORU                ( STOK_RAPOR_VARS *);

#endif // STOK_EKSTRESI_RAPORU_OPEN_H
