#ifndef STOK_MIKTARLARI_RAPORU_OPEN_H
#define STOK_MIKTARLARI_RAPORU_OPEN_H

class QString;

struct STOK_RAPOR_VARS;

QString             GET_STOK_MIKTARLARI_RAPORU              ( STOK_RAPOR_VARS *);

#endif // STOK_MIKTARLARI_RAPORU_OPEN_H
