#ifndef BNK_BANKA_DEFTERI_RAPORU_OPEN_H
#define BNK_BANKA_DEFTERI_RAPORU_OPEN_H

class QString;
struct BNK_RAPOR_VARS;

QString     GET_BNK_BANKA_DEFTERI_RAPORU                        ( BNK_RAPOR_VARS * BNK_RV );

#endif // BNK_BANKA_DEFTERI_RAPORU_OPEN_H
