#ifndef BNK_KK_EKSTRESI_RAPORU_OPEN_H
#define BNK_KK_EKSTRESI_RAPORU_OPEN_H

class QString;
struct BNK_RAPOR_VARS;

QString     GET_BNK_KK_EKSTRESI_RAPORU                          ( BNK_RAPOR_VARS * BNK_RV );

#endif // BNK_KK_EKSTRESI_RAPORU_OPEN_H
