#ifndef MUH_TOPLU_FIS_RAPORU_BATCH_OPEN_H
#define MUH_TOPLU_FIS_RAPORU_BATCH_OPEN_H

class QWidget;

void OPEN_MUH_TOPLU_FIS_RAPORU_BATCH ( QWidget * parent);

#endif // MUH_TOPLU_FIS_RAPORU_BATCH_OPEN_H
