#ifndef MUH_YANSITMA_ISLEMI_BATCH_OPEN_H
#define MUH_YANSITMA_ISLEMI_BATCH_OPEN_H

class QWidget;

void OPEN_MUH_YANSITMA_ISLEMI_BATCH ( QWidget * parent );

#endif // MUH_YANSITMA_ISLEMI_BATCH_OPEN_H
