#ifndef MUH_HESAP_PLANI_RAPORU_BATCH_OPEN_H
#define MUH_HESAP_PLANI_RAPORU_BATCH_OPEN_H

class QWidget;

void OPEN_MUH_HESAP_PLANI_RAPORU_BATCH ( QWidget * parent );

#endif // MUH_HESAP_PLANI_RAPORU_BATCH_OPEN_H
