#ifndef MUHASEBE_ENUM_H
#define MUHASEBE_ENUM_H


#define ONTANIMLI_YANSITMA_HESAPLARI_SAYISI   8

enum HESAP_MODU {
     ENUM_ALT_HESAP           = 0,
     ENUM_ANA_HESAP           = 1,
     ENUM_HESABI_GUNCELLESTIR = 2
};

enum MUHASEBE_FIS_TURLERI{
    ENUM_MAHSUP_FISI  = 0,
    ENUM_TAHSIL_FISI  = 1,
    ENUM_TEDIYE_FISI  = 2,
    ENUM_ACILIS_FISI  = 3,
    ENUM_KAPANIS_FISI = 4

};
enum MUHASEBE_ENTEGRASYON_FIS_TURLERI {
    ENUM_BANKA_ENTEGRASYON_FISI    = 10,
    ENUM_CARI_ENTEGRASYON_FISI     = 11,
    ENUM_CEKSENET_ENTEGRASYON_FISI = 12,
    ENUM_FATURA_ENTEGRASYON_FISI   = 13,
    ENUM_PERAKENDE_ENTEGRASYON_FISI= 14,
    ENUM_PERSONEL_ENTEGRASYON_FISI = 15,
    ENUM_DEMIRBAS_ENTEGRASYON_FISI = 16,
    ENUM_STOK_ENTEGRASYON_FISI     = 17,
    ENUM_IRSALIYE_ENTEGRASYON_FISI = 18,
    ENUM_DIGER_ENTEGRASYON_FISLER  = 21,
    ENUM_SM_MAKBUZ_ENTEGRASYON_FISI= 22

};

enum YVM_HESAP_ORDER {
    ENUM_ORDER_FIS_LINE    = 0,
    ENUM_ORDER_BORC_ALACAK = 1
};

enum MUH_RAPOR_TURLERI {
    ENUM_MUH_HESAP_EKSTRESI       = 0,
    ENUM_MUH_MIZAN_RAPORU         = 1,
    ENUM_MUH_HATALI_FISLER        = 2,
    ENUM_MUH_HESAP_PLANI_RAPORU   = 3,
    ENUM_MUH_TOPLU_FIS_DOKUMU     = 4,
    ENUM_MUH_DEFTERI_KEBIR_RAPORU = 5,
    ENUM_MUH_BILANCO_RAPORU       = 6,
    ENUM_MUH_GELIR_TABLOSU        = 7,
    ENUM_MUH_YEVMIYE_DOKUMU       = 8
};

enum MUH_FIS_TURU {
    ENUM_MUHASEBE_FISI      = 10,
    ENUM_MUHASEBE_ENT_FISI  = 20
};

#endif // MUHASEBE_ENUM_H
