#ifndef MUH_YEVMIYE_NO_OLUSTUR_BATCH_OPEN_H
#define MUH_YEVMIYE_NO_OLUSTUR_BATCH_OPEN_H
class  QWidget;
void OPEN_MUH_YEVMIYE_NO_OLUSTUR_BATCH ( QWidget * parent );

#endif // MUH_YEVMIYE_NO_OLUSTUR_BATCH_OPEN_H
