#ifndef MUH_HESAP_EKSTRESI_RAPORU_OPEN_H
#define MUH_HESAP_EKSTRESI_RAPORU_OPEN_H

#include <QString>
struct MUH_RAPOR_VARS;

QString GET_HESAP_EKSTRESI_RAPORU ( MUH_RAPOR_VARS * rapor_vars );

#endif // MUH_HESAP_EKSTRESI_RAPORU_OPEN_H
