#ifndef MUH_GELIR_TABLOSU_RAPORU_OPEN_H
#define MUH_GELIR_TABLOSU_RAPORU_OPEN_H

#include <QString>
struct   MUH_RAPOR_VARS;

QString GET_GELIR_TABLOSU_RAPORU ( MUH_RAPOR_VARS * rapor_vars );

#endif // MUH_GELIR_TABLOSU_RAPORU_OPEN_H
