#ifndef MUH_YANSITMA_HESAPLARI_FISI_OPEN_H
#define MUH_YANSITMA_HESAPLARI_FISI_OPEN_H

class QWidget;
void OPEN_MUH_YANSITMA_HESAPLARI_FISI (  QWidget * parent );

#endif // MUH_YANSITMA_HESAPLARI_FISI_OPEN_H
