#ifndef ISL_HESAP_OZETI_RAPORU_OPEN_H
#define ISL_HESAP_OZETI_RAPORU_OPEN_H

#include "report_kernel.h"

struct ISL_RAPOR_VARS;

QString GET_ISL_HESAP_OZETI_RAPORU ( ISL_RAPOR_VARS * P_ISL_RV);

#endif // ISL_HESAP_OZETI_RAPORU_OPEN_H
