#ifndef IRSALIYE_ENUM_H
#define IRSALIYE_ENUM_H

enum IRS_SATIRINDA_FATURALANAN_MIKTAR_GUNCELLEME {

    ENUM_IRS_FATURALANAN_MIKTAR_ARTIR       = 0,
    ENUM_IRS_FATURALANAN_MIKTAR_AZALT       = 1,
    ENUM_IRS_FATURALANAN_MIKTAR_GUNCELLE    = 2
};

enum IRS_SATIRINDA_IADE_MIKTARI_GUNCELLEME {

    ENUM_IRS_IADE_MIKTARI_ARTIR = 0,
    ENUM_IRS_IADE_MIKTARI_AZALT = 1
};

enum IRS_FATURA_DURUMU {
    ENUM_FATURALANMIS   = 10,
    ENUM_FATURALANMAMIS = 20
};

enum IRSALIYE_NORMAL_IADE {
    ENUM_IRS_NORMAL = 0,
    ENUM_IRS_IADE   = 1
};

enum IRSALIYE_ALIS_SATIS_TURU {
    ENUM_ALIS_IRSALIYESI    = 0,
    ENUM_SATIS_IRSALIYESI   = 1,
    ENUM_TUM_IRSALIYELER    = 2,
    ENUM_IPTAL_IRSALIYELERI = 3
};

#endif // IRSALIYE_ENUM_H
