#ifndef IRS_IRSALIYE_LISTESI_BATCH_OPEN_H
#define IRS_IRSALIYE_LISTESI_BATCH_OPEN_H

class QWidget;
void OPEN_IRS_IRSALIYE_LISTESI_BATCH ( QWidget * parent );

#endif // IRS_IRSALIYE_LISTESI_BATCH_OPEN_H
