#ifndef IRS_IRSALIYE_LISTESI_RAPORU_OPEN_H
#define IRS_IRSALIYE_LISTESI_RAPORU_OPEN_H

#include <QString>

struct IRSALIYE_RAPOR_VARS;


QString     GET_IRS_IRSALIYE_LISTESI_RAPORU     ( IRSALIYE_RAPOR_VARS * P_IRS_RV );

#endif // IRS_IRSALIYE_LISTESI_RAPORU_OPEN_H
