#ifndef SMM_MAKBUZU_ENUM_H
#define SMM_MAKBUZU_ENUM_H


enum SMM_HIZMET_SEKLI {
     SMM_ALINAN_HIZMET  = 0,
     SMM_SATILAN_HIZMET = 1
};

enum SMM_FIS_TURLERI {
    SMM_ALIS_MAKBUZU  = 10,
    SMM_SATIS_MAKBUZU = 11
};

#endif // SMM_MAKBUZU_ENUM_H
