#ifndef FAT_HIZMET_EKSTRESI_RAPORU_OPEN_H
#define FAT_HIZMET_EKSTRESI_RAPORU_OPEN_H

class QString;
struct FATURA_RAPOR_STRUCT;

QString     GET_FAT_HIZMET_EKSTRESI_RAPORU          ( QString rapor_ismi , FATURA_RAPOR_STRUCT * P_FAT_RV);

#endif // FAT_HIZMET_EKSTRESI_RAPORU_OPEN_H
