#ifndef FAT_HIZMET_EKSTRESI_BATCH_OPEN_H
#define FAT_HIZMET_EKSTRESI_BATCH_OPEN_H

void        OPEN_FAT_HIZMET_EKSTRESI_BATCH          ( QWidget * parent );

#endif // FAT_HIZMET_EKSTRESI_BATCH_OPEN_H
