#ifndef FATURA_ENUM_H
#define FATURA_ENUM_H

enum FAT_FATURA_TURLERI {
    ENUM_FAT_IRSALIYESIZ_ALIS_FATURASI                   = 0,
    ENUM_FAT_IRSALIYELI_ALIS_FATURASI                    = 1,
    ENUM_FAT_HIZMET_ALIS_FATURASI                        = 2,
    ENUM_FAT_VADE_FARKI_ALIS_FATURASI                    = 5,
    ENUM_FAT_HAKEDIS_ALIS_FATURASI                       = 6,
    ENUM_FAT_IRSALIYESIZ_SATIS_FATURASI                  = 7,
    ENUM_FAT_IRSALIYELI_SATIS_FATURASI                   = 8,
    ENUM_FAT_HIZMET_SATIS_FATURASI                       = 9,
    ENUM_FAT_PROFORMA_SATIS_FATURASI                     = 10,
    ENUM_FAT_VADE_FARKI_SATIS_FATURASI                   = 12,
    ENUM_FAT_HAKEDIS_SATIS_FATURASI                      = 13,
    ENUM_FAT_ELLE_IRSALIYE_FATURALASTIRMA_ALIS           = 15,
    ENUM_FAT_ELLE_IRSALIYE_FATURALASTIRMA_SATIS          = 16,
    ENUM_FAT_OTO_IRSALIYE_FATURALASTIRMA_ALIS            = 17,
    ENUM_FAT_OTO_IRSALIYE_FATURALASTIRMA_SATIS           = 18,
    ENUM_FAT_ELLE_IRSALIYE_FATURALASTIRMA_KONSINYE_ALIS  = 19,
    ENUM_FAT_ELLE_IRSALIYE_FATURALASTIRMA_KONSINYE_SATIS = 20,
    ENUM_FAT_FATURA_ARTI_IRSALIYE_SATIS                  = 21,
    ENUM_FAT_FATURA_ARTI_IRSALIYE_ALIS                   = 22
};

enum FATURA_NORNAL_IADE {
    ENUM_FAT_NORMAL = 0,
    ENUM_FAT_IADE   = 1
};

enum FATURA_CINSLERI {
    ENUM_ACIK_FATURA   = 0,
    ENUM_KAPALI_FATURA = 1,
    ENUM_TUM_FATURALAR = 2,
    ENUM_IPTAL_EDILEN_FATURALAR = 3      // sadece fatura listesinde raporlama icin kullnilmistir.
};

enum IRSALIYE_FATURA_ALIS_SATIS_TURU {
    ENUM_ALIS_IRSALIYESI_FATURASI    = 0,
    ENUM_SATIS_IRSALIYESI_FATURASI   = 1
};
enum FATURA_BA_BS_FORMU_TURU {
    ENUM_BA_FORMU   = 0,
    ENUM_BS_FORMU   = 1
};

enum FAT_SATIRINDA_IRSALIYELENEN_MIKTAR_GUNCELLEME {

    ENUM_FAT_IRSALIYELENEN_MIKTAR_ARTIR     = 0,
    ENUM_FAT_IRSALIYELENEN_MIKTAR_AZALT     = 1,
    ENUM_FAT_IRSALIYELENEN_MIKTAR_GUNCELLE  = 2
};

enum FAT_SATIRINDA_IADE_MIKTARI_GUNCELLEME {

    ENUM_FAT_IADE_MIKTARI_ARTIR = 0,
    ENUM_FAT_IADE_MIKTARI_AZALT = 1
};

enum FAT_IRSALIYE_DURUMU {
    ENUM_IRSALIYELENMIS   = 10,
    ENUM_IRSALIYELENMEMIS = 20
};

#endif // FATURA_ENUM_H
