#ifndef FAT_BA_BS_FORMU_LISTESI_BATCH_OPEN_H
#define FAT_BA_BS_FORMU_LISTESI_BATCH_OPEN_H

void        OPEN_FAT_BA_BS_FORMU_LISTESI_BATCH      ( QWidget * parent );

#endif // FAT_BA_BS_FORMU_LISTESI_BATCH_OPEN_H
