#ifndef CARI_HESAP_EKSTRESI_RAPORU_OPEN_H
#define CARI_HESAP_EKSTRESI_RAPORU_OPEN_H

class  QString;
struct CARI_RAPOR_VARS;

QString GET_CARI_HESAP_EKSTRESI_RAPORU ( CARI_RAPOR_VARS * P_CARI_RV);

#endif // CARI_HESAP_EKSTRESI_RAPORU_OPEN_H
