#ifndef CARI_BAKIYE_RAPORU_OPEN_H
#define CARI_BAKIYE_RAPORU_OPEN_H

class QString;
struct CARI_RAPOR_VARS;

QString GET_CARI_BAKIYE_RAPORU ( CARI_RAPOR_VARS * P_CARI_RV);

#endif // CARI_BAKIYE_RAPORU_OPEN_H
