#ifndef PRS_EKSIK_GUN_NEDENLERI_BATCH_OPEN_H
#define PRS_EKSIK_GUN_NEDENLERI_BATCH_OPEN_H

class QWidget;

void          OPEN_PRS_EKSIK_GUN_NEDENLERI_BATCH       ( QWidget * parent    );

#endif // PRS_EKSIK_GUN_NEDENLERI_BATCH_OPEN_H
