#ifndef PRS_EBILDIRGE_OLUSTUR_BATCH_OPEN_H
#define PRS_EBILDIRGE_OLUSTUR_BATCH_OPEN_H


class QWidget;

void          OPEN_PRS_EBILDIRGE_OLUSTUR_BATCH         ( QWidget * parent    );

#endif // PRS_EBILDIRGE_OLUSTUR_BATCH_OPEN_H
