#ifndef PRS_UCRET_PUSULASI_RAPORU_OPEN_H
#define PRS_UCRET_PUSULASI_RAPORU_OPEN_H

class QString;
struct PRS_UCRET_PUSULASI_RAPORU_STRUCT;

QString  GET_PRS_UCRET_PUSULASI_RAPORU ( PRS_UCRET_PUSULASI_RAPORU_STRUCT * P_UCRET_RV );

#endif // PRS_UCRET_PUSULASI_RAPORU_OPEN_H
