#ifndef PRS_IHBAR_VE_KIDEM_TAZMINATI_BATCH_OPEN_H
#define PRS_IHBAR_VE_KIDEM_TAZMINATI_BATCH_OPEN_H

class QWidget;

void          SHOW_PRS_IHBAR_VE_KIDEM_TAZMINATI_BATCH  ( QWidget * parent );

#endif // PRS_IHBAR_VE_KIDEM_TAZMINATI_BATCH_OPEN_H
