#ifndef SUBE_ENTEGRASYON_HESAPLARI_FORMU_OPEN_H
#define SUBE_ENTEGRASYON_HESAPLARI_FORMU_OPEN_H

void    OPEN_SUBE_ENTEGRASYON_HESAPLARI_FORMU   ( int p_sube_id , QWidget * p_parent );

#endif // SUBE_ENTEGRASYON_HESAPLARI_FORMU_OPEN_H
